# You can change this base image to anything else
# But make sure to use the correct version of Java
FROM eclipse-temurin:17.0.17_10-jre-alpine-3.23

# Simply the artifact path
ARG artifact=target/spring-boot-web.jar

WORKDIR /opt/app

RUN "echo ${artifact}"
COPY ${artifact} app.jar

# This should not be changed
ENTRYPOINT ["java","-jar","app.jar"]
